name: fair_front

description: "skhu capstone design : Fair Meeting"

publish_to: 'none' # 공식 배포 예정 시 삭제

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter  # ← 이 줄 추가 (반드시 flutter와 같은 수준에 있어야 함)

  geolocator: ^14.0.0 # GPS

  url_launcher: ^6.3.1
  url_launcher_android: ^6.2.5 #앱으로 연동하도록 사용
  url_launcher_ios: ^6.2.5

  cupertino_icons: ^1.0.8

  http: ^0.13.5         # HTTP 요청을 위해 사용

  kakao_map_sdk: ^1.1.0 # 카카오 맵

  # 카카오 유저 정보 가져오기
  kakao_flutter_sdk_user: ^1.9.7+3
  kakao_flutter_sdk_talk: ^1.9.7+3
  kakao_flutter_sdk_share: ^1.9.7+3

  dotted_border: ^2.0.0                    # 점선 사용

  intl: ^0.19.0                            # cal 패키지

  table_calendar: ^3.0.9                   # 피그마용 달력 ^3.0.9

  flutter_dotenv: ^5.0.2                   # .env 생성 관리

  provider: ^6.1.1

  screen_brightness: ^2.1.3 # 화면 밝기

  shared_preferences: ^2.2.2 # 버튼 저장

  permission_handler: ^11.3.1 #위치 권한 허용

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/kakaoOauth.png
    - assets/markers/
    - .env

  fonts:
    - family: Itim
      fonts:
        - asset: assets/fonts/Itim-Regular.ttf

localizations:
  arb-dir: lib/l10n
  template-arb-file: app_ko.arb
  output-localization-file: app_localizations.dart
  output-class: AppLocalizations
  synthetic-package: true
  supported-locales:
    - ko
    - en

